### ISSUE TITLE
Ordering of entries in Editions Index pane

### ISSUE THREAD

**Issue by sarastanton** [performant-software/chronicleME#100]
## Testing notes

- [ ] On the [QA site Edition page](http://157.245.255.111/#/Edition/1019321), confirm the order of entries in the Index pane are correctly ordered according to the following order, NOT chronological order:

<details>
<summary>order of entries</summary>

1. The year 401
2. The year 407
3. The year 408
4. The year 410
5. The year 412
6. The year 418
7. The year 434
8. The year 435
9. The year 437
10. The year 440
11. The year 446
12. The year 449
13. The year 452
14. The year 460
15. The year 465
16. The year 471
17. The year 471prophecy
18. The year 479
19. The year 481
20. The year 483
21. The year 484
22. The year 487
23. The year 493
24. The year 495
25. The year 496
26. The year 500prologue
27. The year 504
28. The year 516
29. The year 523
30. The year 525
31. The year 526
32. The year 530
33. The year 532
34. The year 534.2
35. The year 536
36. The year 538
37. The year 539
38. The year 540
39. The year 544
40. The year 546cutoff
41. The year 555
42. The year 556
43. The year 561
44. The year 564
45. The year 567
46. The year 568
47. The year 569
48. The year 570
49. The year 571
50. The year 572
51. The year 574
52. The year 575
53. The year 576
54. The year 577
55. The year 585
56. The year 589
57. The year 591
58. The year 592
59. The year 593
60. The year 594
61. The year 595
62. The year 598
63. The year 597
64. The year 600
65. The year 592thoros
66. The year 603
67. The year 605
68. The year 606
69. The year 602b
70. The year 604b
71. The year 609
72. The year 610
73. The year 611

</details>

---

Entries should be in order received from Stemma, not chronological order

---

<details>
<summary>Previous description</summary>

In the "Index" pane of the Editions side bar, the entries are not all in chronological order 

- ex: "The appearance of Tʿoros, c. 592" appears between 495 and 496 but belongs between 591 and 593

**http://localhost:3000/#/Edition/1019321**
</details>

**Comment by sarastanton** [comment]
Before fix:

<img width="565" alt="Screen Shot 2020-07-13 at 5 07 04 PM" src="https://user-images.githubusercontent.com/20568337/87358544-a8886c80-c52b-11ea-9063-5cd46c340a6b.png">

**Comment by blms** [comment]
Reopening as they are still in the wrong order
