### ISSUE TITLE
Text on main page doesn't appear

### ISSUE THREAD

**Issue by tla** [performant-software/chronicleME#125]
## testing notes (round 2)

- [ ] On the [QA site](http://157.245.255.111/), confirm that the first section of the lemma text and translation appear on both `/#/Home` and `/#/`

---

The front page should have the first section (or even just first paragraph) of the edited text, along with the parallel translation; at the moment the headers "Lemma Text" and "Lemma Translation" appear, but the text itself doesn't.

**Comment by blms** [comment]
Still not working when using the base path, /, instead of a subpath of the domain (/Home).
