### ISSUE TITLE
Persons list view

### ISSUE THREAD

**Issue by blms** [performant-software/chronicleME#141]
## testing notes (qa)

In the [QA site](http://157.245.255.111/#/):

- [ ] Confirm there is now no tab in the navigation called "Visualizations", and there is one called "Exploration"
- [ ] Click on "Exploration" and confirm "Persons" is linked from there
- [ ] Click on "Persons" and confirm you get a list of names
  - [ ] Confirm the "in edition" links link back to Edition pages
  - [ ] Confirm the "Learn More" links take you to external pages about the person
- [ ] From the Edition, click "View Options" and check "Persons", then click on a blue highlighted name and confirm it takes you to a specific person in the Persons list view

## dev notes

From 8/17 meeting brainstorming session.

- [x] Update generate data scripts to create persons list and persons lookup
- [x] Create new list view for Persons
  - [x] Names in section --> link to entry in list view
  - [x] Names in list --> link back to the section in which they appear
  - [x] Alphabetically sorted by identifier
  - [x] Include links to external data source
- [x] Move under Visualizations and rename to "Exploration"

example record:
```json
{
    "id": 1617062,
    "label": "PERSON",
    "properties": {
        "identifier": "Anania Mok‘ac‘i",
        "datasource": "Wikipedia",
        "href": "https://en.wikipedia.org/wiki/Ananias_I_of_Armenia"
    },
    "links": [{ "type": "REFERENCED", "follow": null, "target": 1617132 }],
    "primary": true
}
```

**Comment by SteveMarvin** [comment]
looks good

**Comment by SteveMarvin** [comment]
sorry, accidentally closed
