### ISSUE TITLE
Enable Histogram

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#15]

**Comment by melozzo** [comment]
![Screen Shot 2020-01-22 at 11 59 16 AM](https://user-images.githubusercontent.com/4933052/72929457-b7c1f680-3d0e-11ea-8468-7966a9e77c52.png)

what we know: per word - how many witnesses for that word
rank: - the order of the words

if several different nodes all have rank 1 
then that means several different witnesses start off
with a different word

currently the histogram is showing how many times a word shows up in the same position ( order ) across readings - example five different readings start, "in the year 505" , while others might start "it was the year 505" .  would you rather know how many mentioned "505" or how many had the word 505 as the forth word in the sentence?  Or would you like to know both?

**Comment by SteveMarvin** [comment]
Histogram enabled
