### ISSUE TITLE
sort sentences in translation, should be in sequential order

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#20]

**Comment by SteveMarvin** [comment]
I am seeing wide discrepancies between the order and content of the text and its translation. Example: 
![Screen Shot 2020-01-16 at 12 47 06 PM](https://user-images.githubusercontent.com/18423533/72549604-03802600-385f-11ea-8046-1608258b3fbb.png)

**Comment by SteveMarvin** [comment]
I am assured this is good.
