### ISSUE TITLE
Handle When title doesnt confirm to  split with dash -

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#38]
the year 456 - for example

**Comment by SteveMarvin** [comment]
I don't really understand what this issue means...

**Comment by SteveMarvin** [comment]
Moving to rejected to bring attention to problem

**Comment by SteveMarvin** [comment]
I _still_ don't understand what this issue is supposed to mean. What was the problem? 

"Handle When title doesn't confirm to split with dash" just isn't parsing for me, I'm sorry.
