### ISSUE TITLE
selection bugs

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#39]
selecting a rank on histogram should zoom graph to that rank

should also highlight the word at that rank in any armenian text 

there are many types of selection - we might want to specify a list of all the expected behaviours to review 

ie - select a sentence in english - it highlights everywhere else 

select a node on the graph - and it highlights in the text if its there

( if you highlight a node from witness B and you are looking at witness C  - it might not be  in the C text - but the graph should indicate where things split off )

and more... this could use better definition,

**Comment by SteveMarvin** [comment]
Very close:
1. Selecting a rank on histogram does zoom the graph to that node and highlight it
2. Selecting the rank on histogram does **NOT** automatically select the associated word
3. However, clicking the already highlighted node then highlights the Armenian word in the text

**Comment by SteveMarvin** [comment]
Reloading cache after reset fixed this...ACCEPTED
