### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/chronicleME#42]
Add a search bar to the top right corner of the main menu. When the user enters a search term here and presses the return key, they are taken to the search results page.

**Comment by SteveMarvin** [comment]
Not sure if this is ready for prime time:

When I enter a search term (in English) that I know exists on another page, I get a popup that looks like this:
![Screen Shot 2020-02-20 at 10 22 26 AM](https://user-images.githubusercontent.com/18423533/74949132-4dfb4200-53cb-11ea-9ad7-ab96855002d1.png)
...but nothing else. Clicking OK dismisses the popup but does not take me to a search results page.

**Comment by SteveMarvin** [comment]
Misunderstanding on my part. Apparently the results page is in another issue, and this is the expected behavior for this issue. ACcepted!
