### ISSUE TITLE
Navigation rolls under the graph

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/chronicleME#49]
The previous and next buttons in the edition reading interface can be obscured by the graph when the reading text is scrolled.

**Comment by SteveMarvin** [comment]
This is still happening. Prev and Next buttons can be scrolled completely out of sight. 
![Screen Shot 2020-02-13 at 12 50 53 PM](https://user-images.githubusercontent.com/18423533/74463226-8517a380-4e5f-11ea-91cd-40dae83d1b55.png)
![Screen Shot 2020-02-13 at 12 51 25 PM](https://user-images.githubusercontent.com/18423533/74463252-91036580-4e5f-11ea-9298-eb81bb1457d2.png)

**Comment by SteveMarvin** [comment]
Fixed!
