### ISSUE TITLE
Edition page

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/chronicleME#5]
Implement a cover page for the edition that is accessible off of the main menu. This page includes an abstract and a grid of thumbnail cards that lead into the sections of the Chronicle. (Prologue, Section 1-3). For now, all of these cards should link to the Year 401.

**Comment by NickLaiacona** [comment]
This page will be similar to the attached wireframe:

![Screen Shot 2019-10-30 at 3 33 30 PM](https://user-images.githubusercontent.com/11439/67892323-de66fb80-fb2a-11e9-8542-7da7f951ed76.png)

**Comment by SteveMarvin** [comment]
Looking good!
