### ISSUE TITLE
mobile site needs to prevent images from compressing horizontally

### ISSUE THREAD

**Issue by SteveMarvin** [performant-software/chronicleME#50]

**Comment by SteveMarvin** [comment]
Latest iOS Safari:
![The Chronicle of Matthew of Edessa](https://user-images.githubusercontent.com/18423533/81085398-2a716f00-8ec5-11ea-85c5-5726c6acc0f9.png)

Same on mobile Chrome.

**Comment by sarastanton** [comment]
Should be resizing properly now

**Comment by SteveMarvin** [comment]
so it is!
