### ISSUE TITLE
Chronicle home page

### ISSUE THREAD

**Issue by NickLaiacona** [performant-software/chronicleME#7]
The Home page should display a brief introductory paragraph follow by a separator and then the first section of the Chronicle. Buttons at the bottom should make it easy for the user to continue reading.

**Comment by NickLaiacona** [comment]
This screen will be similar in layout to the attached wireframe:

![Screen Shot 2019-10-30 at 3 33 53 PM](https://user-images.githubusercontent.com/11439/67892285-cabb9500-fb2a-11e9-86b4-dfadd5685d9e.png)

**Comment by SteveMarvin** [comment]
I see no buttons on the bottom to help me along. If I don't know to go to the nav bar and hit Edition, I'm stuck.

**Comment by SteveMarvin** [comment]
accepting this and opening new issue for buttons :  #32
