### ISSUE TITLE
view options- date should highlight the phrase where date is mentioned

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#76]
certain sections are highlighting large amounts of text when date reference is highlighted - possibly caused by using node id instead of rank to

**Comment by melozzo** [comment]
the solution was to look up the nodes by rank, since only rank ( rather than nodeId ) is consistently sequential - also I discovered that some of the place references have begin and end reversed - the code checks for this and always puts the lower rank first -

**Comment by melozzo** [comment]
Steve:  problem sections before were the years 460 and 577 for example

**Comment by SteveMarvin** [comment]
Thanks very much for the examples! ;-)
