### ISSUE TITLE
Manuscript View

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#83]
( repeat of lost ticket )
- remove header info
- format tei-lb as block not inline
- format tei-notes as italic
- format tei-damaged with brackets around it
- insert links at section breaks to edition page- with the selected manuscript/witness

**Comment by SteveMarvin** [comment]
It's a little hard to tell when everything is in Armenian, but this seems to look good.

**Comment by SteveMarvin** [comment]
Have not found an example of tei-damaged to examine
