### ISSUE TITLE
Oxford Manuscript Image

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#84]
( repeat of lost ticket )
Display Image of manuscript pages alongside Manuscript tei transcription, using OpenSeaDragon 

- float thumbnails right, 
- on hover show a border to indicate they are clickable
- split text and enlarged image 50/50
- responsive layout - don't show enlarged image and disable clicking on thumbs on small screen

**Comment by SteveMarvin** [comment]
All manuscripts return a 404 error and display a broken image icon.

**Comment by SteveMarvin** [comment]
![image](https://user-images.githubusercontent.com/18423533/80505434-511e2b80-8942-11ea-9aad-76867d9a1b00.png)
