### ISSUE TITLE
Firefox Issues -

### ISSUE THREAD

**Issue by melozzo** [performant-software/chronicleME#88]
## testing notes

Using Firefox (and other browsers), in the [QA site](http://157.245.255.111/), open the Edition. Under "View Options," turn on the graph.
- [ ] Confirm the graph starts out with the "start" node visible
- [ ] Click on a different word in the lemma text (left text pane) and confirm the graph scrolls to the node for that word

Note that you may encounter the issue in #139: tracking separately since it's slightly different (and much more difficult!)

---

- graph scrolling and highlights 
- also initial position of graph

no good in firefox

**Comment by melozzo** [comment]
this might be another good reason to use the js graph-vis component - maybe it will solve the firefox issues ( or maybe just an alternate syntax is needed - something to keep in mind )

**Comment by SteveMarvin** [comment]
perfecto
