### ISSUE TITLE
Heat map sizing

### ISSUE THREAD

**Issue by sarastanton** [performant-software/chronicleME#91]
** Updated ** 

Reduce the height of the heat map by reducing top and bottom margin and reducing size of graph itself by 30%.

**http://157.245.255.111/#/Edition/1019321**

**Comment by SteveMarvin** [comment]
Hard to tell without a comparison to work from, however, there is a difference between the look of it when in a non-full-size window, and when it is maximized onscreen. Sara reports that even full screen on a small monitor, it shows the compressed version.
Windowed:
![image](https://user-images.githubusercontent.com/18423533/87072871-7ead0e00-c1ea-11ea-976e-324a618507e4.png)
Full-screen:
![image](https://user-images.githubusercontent.com/18423533/87072918-908eb100-c1ea-11ea-9bda-17c3a9237e38.png)

**Comment by sarastanton** [comment]
***Updated - padding should now stay at consistent ratio with container regardless of screen/viewport size ***

**Comment by SteveMarvin** [comment]
It does!
