### ISSUE TITLE
Research partial word search and implement if possible

### ISSUE THREAD

**Issue by sarastanton** [performant-software/chronicleME#97]
- Lunr docs:  https://lunrjs.com/guides/searching.html

- Ex: 'south' should bring up results for 'southern'; 'earth' should bring up results for 'earth' AND 'earthquake' ; 'eart' should bring up results with 'earth' AND 'earthquake' AND 'heart' etc

- Short text strings (i.e. 'the', 'an') should also work

- Armenian search results should return year groups with a list of witnesses and a link to the corresponding Edition section.

- Armenian strings to test: "երկր", "կոտորած"

- Note: "Year unavailable" is an expected result if the linked section does not display a year in the Editions view (ex: section 962909)

**Comment by NickLaiacona** [comment]
This works for the English words I have tried. However, short and common terms 'the' 'an' cause the page to go blank with javascript errors in console.
