### ISSUE TITLE
Editions - Remove download message

### ISSUE THREAD

**Issue by sarastanton** [performant-software/chronicleME#99]
Remove this message from Edition Home (**http://157.245.255.111/#/Edition**):

> Download the Armenian text as JSON or TEI

<img width="1396" alt="Screen Shot 2020-07-07 at 4 23 25 PM" src="https://user-images.githubusercontent.com/20568337/86845410-1554c000-c06f-11ea-8ed6-a6f1695b4f64.png">

**Comment by SteveMarvin** [comment]
It's gone!

**Comment by NickLaiacona** [comment]
This appears to be fixed on staging.
